# name: Deploy Model to GCP Cloud Run

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Authenticate to GCP
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Set up gcloud
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}

#       - name: Configure Docker
#         run: gcloud auth configure-docker --quiet

#       - name: Build Docker image 
#         run: |
#           docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ml-model .

#       - name: Push Docker image 
#         run: |
#           docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ml-model

#       - name: Deploy to Cloud Run 
#         run: |
#           gcloud run deploy ml-model \
#             --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/ml-model \
#             --platform managed \
#             --region ${{ secrets.GCP_REGION }} \
#             --allow-unauthenticated
